version: 2.1

jobs:
  service2-say-hello:
    executor: common-executor
    environment:
      MY_NAME: << pipeline.parameters.common-my-name >>
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, ${MY_NAME}!2"

workflows:
  service2-say-hello-workflow:
    jobs:
      - common-say-hello
      - service2-say-hello
